version: '3.8'

services:
  backend:
    build: ./mern-demo/server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb+srv://chidungsamsung123_db_user:Dung123456789@cluster0.ryn9pcy.mongodb.net/cloud_lab?retryWrites=true&w=majority
    networks:
      - mern-net

  frontend:
    build: ./mern-demo/client
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mern-net

networks:
  mern-net:
    driver: bridge